version: "3"

services:
  frontend:
    depends_on:
      matching-service:
        condition: service_started
      collaboration-service:
        condition: service_started
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - 3000:3000

  collaboration-service:
    container_name: collaboration-service
    build:
      context: ./backend/collaboration-service
      dockerfile: Dockerfile
    ports:
      - "5005:8080" # Maps container port 8080 to local 5005

  matching-service:
    container_name: matching-service
    build:
      context: ./backend/matching-service
      dockerfile: Dockerfile
    ports:
      - "5007:8080" # Maps container port 8080 to local 5007