export const rows = [
    {id: 1, title:  "Reverse a String", category:  ["Strings", "Algorithms"], complexity:  "Easy"},
    {id: 2, title:  "Linked List Cycle Detection", category:  ["Data Structures", "Algorithms"], complexity:  "Easy"},
    {id: 3, title:  "Roman to Integer", category:  ["Algorithms"], complexity:  "Easy" },
    {id: 4, title:  "Add Binary Bit Manipulation", category:  ["Algorithms"], complexity:  "Easy" },
    {id: 5, title:  "Fibonacci Number Recursion", category:  ["Algorithms"], complexity:  "Easy" },
    {id: 6, title:  "Implement Stack using Queues", category:  ["Data Structures"], complexity:  "Easy"},
    {id: 7, title:  "Combine Two Tables", category:  ["Databases"], complexity:  "Easy" },
    {id: 8, title:  "Repeated DNA Sequences", category:  ["Algorithms", "Bit Manipulation"], complexity:  "Medium"},
    {id: 9, title:  "Course Schedule", category:  ["Data Structures", "Algorithms"], complexity:  "Medium"},
    {id: 10, title:  "LRU Cache Design", category:  ["Data Structures"], complexity:  "Medium"},
    {id: 11, title:  "Longest Common Subsequence Strings", category:  ["Algorithms"], complexity:  "Medium"},
    {id: 12, title:  "Rotate Image Arrays", category:  ["Algorithms"], complexity:  "Medium"},
    {id: 13, title:  "Airplane Seat Assignment Probability", category:  ["Brainteaser"], complexity:  "Medium"},
    {id: 14, title:  "Validate Binary Search Tree", category:  ["Data Structures", "Algorithms"], complexity:  "Medium"},
    {id: 15, title:  "Sliding Window Maximum Arrays", category:  ["Algorithms"], complexity:  "Hard" },
    {id: 16, title:  "N-Queen Problem", category:  ["Algorithms"], complexity:  "Hard"},
    {id: 17, title:  "Serialize and Deserialize a Binary Tree", category:  ["Data Structures", "Algorithms"], complexity:  "Hard"},
    {id: 18, title:  "Wildcard Matching Strings", category:  ["Algorithms"], complexity:  "Hard"  },
    {id: 19, title:  "Chalkboard XOR Game", category:  ["Brainteaser"], complexity:  "Hard"},
    {id: 20, title:  "Trips and Users", category:  ["Databases"], complexity:  "Hard" },
];

export const questionsDescription = [
    {id: 1, description: "Write a function that reverses a string. The input string is given as an array of characters s.\n\nYou must do this by modifying the input array in-place with O(1) extra memory.\n\nExample 1:\n\nInput: s = ['h','e','l','l','o']\nOutput: ['o','l','l','e','h']\n\nConstraints:\n1 <= s.length <= 105\ns[i] is a printable ascii character."},
    {id: 2, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 3, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 4, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 5, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 6, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 7, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 8, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 9, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 10, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 11, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 12, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 13, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 14, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 15, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 16, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 17, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 18, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 19, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},
    {id: 20, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Rem repellendus, repudiandae libero possimus illum itaque exercitationem. Voluptas veniam deleniti modi nam facilis ipsum sapiente vitae eos impedit tenetur labore asperiores quas tempora, odio ratione culpa ipsa in maxime ad commodi officia voluptatum! Nesciunt est, expedita fuga cupiditate harum ad totam laudantium, similique commodi eos quo tenetur impedit autem obcaecati officia! Cupiditate itaque nostrum odit ducimus provident amet non sapiente necessitatibus recusandae alias ratione at perspiciatis explicabo minima dignissimos delectus nisi deleniti, dolor, aspernatur qui perferendis reiciendis beatae ad. Est rerum perspiciatis, totam nostrum eaque voluptate libero molestiae soluta animi rem."},

];

const tableColumns = ['id', 'title', 'category', 'complexity', 'actions'];
export const columns = tableColumns.map(col =>  {return {key: col, label: col.toUpperCase()}});

export const complexityColorMap = {
    Easy: "success",
    Medium: "warning",
    Hard: "danger",
}

export const categories = ['Algorithms', 'Data Structure', 'BrainTeaser', 'Strings', 'Bit Manipulation', 'Dynamic Programming']