# syntax=docker/dockerfile:1

FROM golang:1.20-alpine AS builder

WORKDIR /usr/src/app

RUN go install github.com/cosmtrek/air@latest

COPY . .

RUN go mod tidy

# Expose port 8080 to the outside world
EXPOSE 8080

CMD air