version: '3'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "1234:1234"
    volumes:
      - .:/usr/src/app
    networks:
      - peerpreps-backend
    depends_on:
      db-agw:
        condition: service_healthy

  db-agw:
    image: postgres:16rc1-alpine3.18
    container_name: postgres-api-gateway
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGUSER=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "apigateway", "-p", "5433" ]
      interval: 5s
      timeout: 60s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - peerpreps-backend

volumes:
  data:

networks:
  peerpreps-backend:
    external: true
