version: '3'

services:
  question-service:
    container_name: question-service
    build:
      dockerfile: Dockerfile.stage
    ports:
      - "5008:8080"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0.1
    container_name: mongodb
    restart: always
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data: