version: '3'

services:
  question-service:
    container_name: question-service
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mongo:7.0.1
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - backend
volumes:
  db-data:

networks:
  backend:
    external: true
