version: '3'

services:
  question-service:
    container_name: question-service
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "5008:8080"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - peerpreps-backend

  mongodb:
    image: mongo:7.0.1
    container_name: mongodb
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - peerpreps-backend

volumes:
  db-data:

networks:
  peerpreps-backend:
    external: true
