export enum Language {
  C_PLUS_PLUS = 'CPP',
  JAVA = 'JAVA',
  PYTHON_THREE = 'PYTHON',
  C = 'C',
  C_SHARP = 'CSHARP',
  JAVASCRIPT = 'JAVASCRIPT',
  RUBY = 'RUBY',
  SWIFT = 'SWIFT',
  GO = 'GO',
  KOTLIN = 'KOTLIN',
  RUST = 'RUST',
  PHP = 'PHP',
  TYPESCRIPT = 'TYPESCRIPT',
  ELIXIR = 'ELIXIR',
  DART = 'DART',
}

export const LANGUAGES = Object.freeze([
  Language.C,
  Language.C_PLUS_PLUS,
  Language.C_SHARP,
  Language.DART,
  Language.ELIXIR,
  Language.GO,
  Language.JAVA,
  Language.JAVASCRIPT,
  Language.KOTLIN,
  Language.PHP,
  Language.PYTHON_THREE,
  Language.RUBY,
  Language.RUST,
  Language.SWIFT,
  Language.TYPESCRIPT,
]);
