export enum Language {
    NO_LANGUAGE = '',
    C_PLUS_PLUS = 'C_PLUS_PLUS',
    JAVA = 'JAVA',
    PYTHON_THREE = 'PYTHON_THREE',
    C = 'C',
    C_SHARP = 'C_SHARP',
    JAVASCRIPT = 'JAVASCRIPT',
    RUBY = 'RUBY',
    SWIFT = 'SWIFT',
    GO = 'GO',
    SCALA = 'SCALA',
    KOTLIN = 'KOTLIN',
    RUST = 'RUST',
    PHP = 'PHP',
    TYPESCRIPT = 'TYPESCRIPT',
    RACKET = 'RACKET',
    ERLANG = 'ERLANG',
    ELIXIR = 'ELIXIR',
    DART = 'DART',
    COBOL = 'COBOL',
    LISP = 'LISP',
    F_SHARP = 'F_SHARP',
    FORTRAN = 'FORTRAN',
    HASKELL = 'HASKELL',
    OBJECTIVE_C = 'OBJECTIVE_C',
    OCAML = 'OCAML',
    PASCAL = 'PASCAL',
    PROLOG = 'PROLOG',
  }

export const LANGUAGES = Object.freeze([
    Language.NO_LANGUAGE,
    Language.C,
    Language.C_PLUS_PLUS,
    Language.C_SHARP,
    Language.COBOL,
    Language.DART,
    Language.ELIXIR,
    Language.ERLANG,
    Language.F_SHARP,
    Language.FORTRAN,
    Language.GO,
    Language.HASKELL,
    Language.JAVA,
    Language.JAVASCRIPT,
    Language.KOTLIN,
    Language.LISP,
    Language.OBJECTIVE_C,
    Language.OCAML,
    Language.PASCAL,
    Language.PHP,
    Language.PROLOG,
    Language.PYTHON_THREE,
    Language.RACKET,
    Language.RUBY,
    Language.RUST,
    Language.SCALA,
    Language.SWIFT,
    Language.TYPESCRIPT,
  ]);
  