name: Lint

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'backup/**'
      - '**/*.draft.md'
      - '**/*.toml'
      - '**/*.yaml'
      - '.gitignore'
      - 'Dockerfile.*'

jobs:
  linelint:
    runs-on: ubuntu-latest
    name: Check if all files end in newline
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Linelint
        uses: fernandrone/linelint@master
        id: linelint
